# ---------- Module 2: GPT-based Financial Planner ----------

import openai

def gpt_financial_advice(user_context):
    """
    Generates financial advice using OpenAI's GPT-4 model based on the user's financial context.

    Args:
        user_context (str): A string describing the user's financial situation.

    Returns:
        str: A string containing the financial advice generated by the GPT-4 model.
    """
    # Replace with your actual OpenAI API key
    openai.api_key = 'htpps:fdghjkl;koij35378$#%&*..'

    # Create the prompt to be sent to the GPT-4 model
    prompt = f"""
    You are a smart financial assistant. A user has the following context:
    {user_context}
    Provide them with budgeting, saving, and investing advice.
    """

    # Make the API call to OpenAI's ChatCompletion endpoint
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a helpful financial advisor."},
            {"role": "user", "content": prompt}
        ]
    )

    # Extract and return the content of the response
    return response['choices'][0]['message']['content']
